apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: spam2000  
  namespace: argocd  
spec:  
  project: default  
  source:  
    repoURL: https://github.com/mstohnii/gitops-project-workshop.git  
    targetRevision: main  
    path: charts/spam2000  
    helm:  
      valueFiles:  
        - values.yaml  
  destination:  
    server: https://kubernetes.default.svc  
    namespace: spam2000  
  syncPolicy:  
    automated:  
      prune: true  
      selfHeal: true  
    syncOptions:  
      - CreateNamespace=true  
